### ISSUE TITLE
Ошибки при компиляции TypeScript

### ISSUE THREAD

**Issue by daniluk4000** [negezor/vk-io#214]
#### What version of `vk-io` are you using?
4.0.0-rc.22 (всё было ок на rc.21)

#### What version of Node.js are you using?
v12.11.0, Typescript v3.6.4

#### What did you do?
Скомпилировал проект

#### What did you expect to happen?
Проект не скомпилировался с ~20 ошибками
Например: 
`vk-io/lib/api/schemas/responses.d.ts:1332:21 - error TS2300: Duplicate identifier 'StorageGetKeysResponse'.`
`/vk-io/lib/structures/contexts/comment-action.d.ts:27:54 - error TS2304: Cannot find name 'Omit'`

#### What was the actual result?
Проект скомпилировался без ошибок vk-io

**Comment by Satont** [comment]
Same problem here.

**Comment by Satont** [comment]
Teprorary solution is: add `"skipLibCheck": true` to `tsconfig.json`.

**Comment by daniluk4000** [comment]
Thanks!

**Comment by negezor** [comment]
What is in the TypeScript config? I checked on 3.6.4 with this configuration, the assembly is successful.
```json
{
	"compilerOptions": {
		"target": "esnext",
		"module": "esnext",
		"lib": ["esnext"],
		"moduleResolution": "node",
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true,
		"declaration": true,
		"sourceMap": false,
		"strict": true
	}
}
```

**Comment by Satont** [comment]
```json
{
"compilerOptions": {
  "target": "es6",
  "strictPropertyInitialization": false,
  "module": "commonjs",
  "incremental": true,
  "removeComments": true,
  "noImplicitAny": false,
  "noImplicitThis": true,
  "noUnusedLocals": true,
  "esModuleInterop": true,
  "moduleResolution": "node",
  "emitDecoratorMetadata": true,
  "experimentalDecorators": true,
  "declaration": false,
  "noResolve": false,
  "baseUrl": "src/bot",
  "outDir": "../dest",
  "inlineSourceMap": true,
  "skipLibCheck": true
  },
  "exclude": [
    "node_modules"
  ]
}
```

TS 3.6.4

**Comment by negezor** [comment]
Ошибка должна быть исправлена в `4.0.0-rc.23`.

**Comment by maxxxpavlov** [comment]
`node_modules/vk-io/lib/structures/attachments/document.d.ts:100:5 - error TS2416: Property '[inspectCustomData]' in type 'DocumentAttachment' is not assignable to the same property in base type 'Attachment<IDocumentAttachmentPayload>'.
  Type '() => object | null' is not assignable to type '() => object'.
    Type 'object | null' is not assignable to type 'object'.
      Type 'null' is not assignable to type 'object'.

100     [inspectCustomData](): object | null;
        ~~~~~~~~~~~~~~~~~~~

node_modules/vk-io/lib/structures/attachments/photo.d.ts:81:5 - error TS2416: Property '[inspectCustomData]' in type 'PhotoAttachment' is not assignable to the same property in base type 'Attachment<IPhotoAttachmentPayload>'.
  Type '() => object | null' is not assignable to type '() => object'.
    Type 'object | null' is not assignable to type 'object'.
      Type 'null' is not assignable to type 'object'.

81     [inspectCustomData](): object | null;
       ~~~~~~~~~~~~~~~~~~~

node_modules/vk-io/lib/structures/attachments/story.d.ts:138:5 - error TS2416: Property '[inspectCustomData]' in type 'StoryAttachment' is not assignable to the same property in base type 'Attachment<IStoryAttachmentPayload>'.
  Type '() => object | undefined' is not assignable to type '() => object'.
    Type 'object | undefined' is not assignable to type 'object'.
      Type 'undefined' is not assignable to type 'object'.

138     [inspectCustomData](): object | undefined;
        ~~~~~~~~~~~~~~~~~~~

node_modules/vk-io/lib/structures/attachments/wall.d.ts:216:5 - error TS2416: Property '[inspectCustomData]' in type 'WallAttachment' is not assignable to the same 
property in base type 'Attachment<IWallAttachmentPayload>'.
  Type '() => object | null' is not assignable to type '() => object'.
    Type 'object | null' is not assignable to type 'object'.
      Type 'null' is not assignable to type 'object'.

216     [inspectCustomData](): object | null;
        ~~~~~~~~~~~~~~~~~~~


Found 4 errors.`

**Comment by negezor** [comment]
Должно заработать правильно в `vk-io@4.0.0-rc.26`.

**Comment by negezor** [comment]
Закрою вопрос из-за отсутствия активности, но проблема должна быть уже решена.

**Comment by daniluk4000** [comment]
node_modules/vk-io/lib/collect/collect.d.ts:7:15 - error TS2411: Property 'vk' of type 'VK' is not assignable to string index type '{ [key: string]: <T = Record<string, any>>(options: Record<string, any> & { parallelCount?: number; count?: number; offset?: number; }) => CollectStream<T>; }'.

7     protected vk: VK;
                ~~

node_modules/vk-io/lib/collect/collect.d.ts:19:5 - error TS2411: Property 'chain' of type '() => Chain' is not assignable to string index type '{ [key: string]: <T = Record<string, any>>(options: Record<string, any> & { parallelCount?: number; count?: number; offset?: number; }) => CollectStream<T>; }'.

19     chain(): Chain;
       ~~~~~

node_modules/vk-io/lib/collect/collect.d.ts:23:5 - error TS2411: Property 'executes' of type '(method: string, queue: Record<string, any>[]) => Promise<{ response: any[]; errors: any[]; }>' is not assignable to string index type '{ [key: string]: <T = Record<string, any>>(options: Record<string, any> & { parallelCount?: number; count?: number; offset?: number; }) => CollectStream<T>; }'.

23     executes(method: string, queue: Record<string, any>[]): Promise<{
       ~~~~~~~~

**Comment by negezor** [comment]
Made a fix in the commit https://github.com/negezor/vk-io/commit/a2651518ace582e5819304302dc82b26c887a6b1. Should work on `4.0.0-rc.29`.
