### ISSUE TITLE
Add support for @types/node >13.9.7

### ISSUE THREAD

**Issue by daniluk4000** [negezor/vk-io#279]
#### What did you do?
Updated @types/node to latest version: 14.0.1

#### What did you expect to happen?
My beloved project can compile with @types/node up to 14.0.1

#### What was the actual result?

node_modules/vk-io/lib/collect/stream.d.ts:62:5` - error TS2416: Property 'on' in type 'CollectStream<T>' is not assignable to the same property in base type 'Readable'.
  Type '{ (event: "close", listener: () => void): this; (event: "data", listener: (chunk: ICollectChunkData<T>) => void): this; (event: "end", listener: () => void): this; (event: "readable", listener: () => void): this; (event: "error", listener: (err: Error) => void
): this; }' is not assignable to type '{ (event: "close", listener: () => void): this; (event: "data", listener: (chunk: any) => void): this; (event: "end", listener: () => void): this; (event: "error", listener: (err: Error) => void): this; (event: "pause", listener:
 () => void): this; (event: "readable", listener: () => void): this; (event: "resume", l...'.
    Types of parameters 'event' and 'event' are incompatible.
      Type '"pause"' is not assignable to type '"close"'.

62     on(event: 'close', listener: () => void): this;
       ~~

node_modules/vk-io/lib/collect/stream.d.ts:63:5 - error TS2416: Property 'on' in type 'CollectStream<T>' is not assignable to the same property in base type 'Readable'.
  Type '{ (event: "close", listener: () => void): this; (event: "data", listener: (chunk: ICollectChunkData<T>) => void): this; (event: "end", listener: () => void): this; (event: "readable", listener: () => void): this; (event: "error", listener: (err: Error) => void
): this; }' is not assignable to type '{ (event: "close", listener: () => void): this; (event: "data", listener: (chunk: any) => void): this; (event: "end", listener: () => void): this; (event: "error", listener: (err: Error) => void): this; (event: "pause", listener:
 () => void): this; (event: "readable", listener: () => void): this; (event: "resume", l...'.

63     on(event: 'data', listener: (chunk: ICollectChunkData<T>) => void): this;
       ~~

node_modules/vk-io/lib/collect/stream.d.ts:64:5 - error TS2416: Property 'on' in type 'CollectStream<T>' is not assignable to the same property in base type 'Readable'.
  Type '{ (event: "close", listener: () => void): this; (event: "data", listener: (chunk: ICollectChunkData<T>) => void): this; (event: "end", listener: () => void): this; (event: "readable", listener: () => void): this; (event: "error", listener: (err: Error) => void
): this; }' is not assignable to type '{ (event: "close", listener: () => void): this; (event: "data", listener: (chunk: any) => void): this; (event: "end", listener: () => void): this; (event: "error", listener: (err: Error) => void): this; (event: "pause", listener:
 () => void): this; (event: "readable", listener: () => void): this; (event: "resume", l...'.

64     on(event: 'end', listener: () => void): this;
       ~~

node_modules/vk-io/lib/collect/stream.d.ts:65:5 - error TS2416: Property 'on' in type 'CollectStream<T>' is not assignable to the same property in base type 'Readable'.
  Type '{ (event: "close", listener: () => void): this; (event: "data", listener: (chunk: ICollectChunkData<T>) => void): this; (event: "end", listener: () => void): this; (event: "readable", listener: () => void): this; (event: "error", listener: (err: Error) => void
): this; }' is not assignable to type '{ (event: "close", listener: () => void): this; (event: "data", listener: (chunk: any) => void): this; (event: "end", listener: () => void): this; (event: "error", listener: (err: Error) => void): this; (event: "pause", listener:
 () => void): this; (event: "readable", listener: () => void): this; (event: "resume", l...'.

65     on(event: 'readable', listener: () => void): this;
       ~~

node_modules/vk-io/lib/collect/stream.d.ts:66:5 - error TS2416: Property 'on' in type 'CollectStream<T>' is not assignable to the same property in base type 'Readable'.
  Type '{ (event: "close", listener: () => void): this; (event: "data", listener: (chunk: ICollectChunkData<T>) => void): this; (event: "end", listener: () => void): this; (event: "readable", listener: () => void): this; (event: "error", listener: (err: Error) => void
): this; }' is not assignable to type '{ (event: "close", listener: () => void): this; (event: "data", listener: (chunk: any) => void): this; (event: "end", listener: () => void): this; (event: "error", listener: (err: Error) => void): this; (event: "pause", listener:
 () => void): this; (event: "readable", listener: () => void): this; (event: "resume", l...'.

66     on(event: 'error', listener: (err: Error) => void): this;

#### Additional Info
Broken since 13.9.8, 13.9.7 works fine

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.0.0-rc.30` |
| `node`                             | `12.16.1` |
| `TypeScript`                       | `3.9.2` |
| `npm`                    | `6.14.4` |

**Comment by negezor** [comment]
Temporary solution to use `skipLibCheck: true` in [compilerOptions](https://www.typescriptlang.org/docs/handbook/compiler-options.html).
